<?php include 'includes/header.php';$u=user();$role=$u['role'];$oversight=is_admin()||is_sub_officer();
$stats=[];
if($oversight){foreach(['users','records','work_tasks','operational_reports','students','wastigruh_daily'] as $t){$q=mysqli_query($conn,"SELECT COUNT(*) c FROM $t");$stats[$t]=(int)mysqli_fetch_assoc($q)['c'];}$q=mysqli_query($conn,"SELECT COUNT(*) c FROM users WHERE approval_status='pending'");$pending=(int)mysqli_fetch_assoc($q)['c'];}
else{$it=$u['institution_type'];$code=$u['institution_code'];
foreach([['records','SELECT COUNT(*) c FROM records WHERE institution_type=? AND institution_code=?'],['operational_reports','SELECT COUNT(*) c FROM operational_reports WHERE institution_type=? AND institution_code=?']] as $z){$q=mysqli_prepare($conn,$z[1]);mysqli_stmt_bind_param($q,'ss',$it,$code);mysqli_stmt_execute($q);$stats[$z[0]]=(int)mysqli_fetch_assoc(mysqli_stmt_get_result($q))['c'];}
if($it==='ashram_shala'){$q=mysqli_prepare($conn,"SELECT COUNT(*) c FROM students WHERE institution_code=? AND status='active'");mysqli_stmt_bind_param($q,'s',$code);mysqli_stmt_execute($q);$stats['students']=(int)mysqli_fetch_assoc(mysqli_stmt_get_result($q))['c'];$q=mysqli_prepare($conn,"SELECT COUNT(*) c FROM student_attendance a JOIN students s ON s.id=a.student_id WHERE s.institution_code=? AND a.attendance_date=? AND a.status='present'");$d=today();mysqli_stmt_bind_param($q,'ss',$code,$d);mysqli_stmt_execute($q);$stats['today_present']=(int)mysqli_fetch_assoc(mysqli_stmt_get_result($q))['c'];}
if($it==='wastigruh'){$q=mysqli_prepare($conn,"SELECT * FROM wastigruh_daily WHERE institution_code=? AND report_date=? LIMIT 1");$d=today();mysqli_stmt_bind_param($q,'ss',$code,$d);mysqli_stmt_execute($q);$w=mysqli_fetch_assoc(mysqli_stmt_get_result($q));$stats['residents']=(int)($w['total_residents']??0);$stats['today_present']=(int)($w['present']??0);}
$q=mysqli_prepare($conn,"SELECT COUNT(*) c FROM work_tasks t JOIN task_assignees a ON a.task_id=t.id WHERE a.user_id=? AND t.status NOT IN ('closed','verified')");mysqli_stmt_bind_param($q,'i',$u['id']);mysqli_stmt_execute($q);$stats['open_tasks']=(int)mysqli_fetch_assoc(mysqli_stmt_get_result($q))['c'];}
?>
<div class="page-head"><div><p class="eyebrow">ITDP COMMAND CENTRE</p><h1><?=is_admin()?'Administrator Dashboard':(is_sub_officer()?'Sub Officer Dashboard':(is_clerk()?'Clerk / Data Entry Dashboard':'Institution Dashboard'))?></h1><p class="muted"><?=is_admin()?'District-level administration and approvals.':(is_sub_officer()?'Supervise institutions, reports, users and compliance.':e($u['institution_type'].' · '.$u['institution_code']))?></p></div><div class="actions"><a class="btn primary" href="records/create.php">+ New Record</a><?php if($u['institution_type']==='ashram_shala'):?><a class="btn" href="institution/attendance.php">🎓 Presenty</a><?php elseif($u['institution_type']==='wastigruh'):?><a class="btn" href="institution/wastigruh.php">🏠 Wastigruh Entry</a><?php endif;?></div></div>
<div class="grid stats"><?php foreach($stats as $k=>$v):?><div class="card stat"><span><?=e(ucwords(str_replace('_',' ',$k)))?></span><strong><?=e($v)?></strong><small>Live platform count</small></div><?php endforeach;?></div>
<div class="grid two"><div class="card"><h3><?=is_sub_officer()?'Supervision centre':(is_clerk()?'Daily data entry':'Quick workspace')?></h3><div class="quick"><?php if(is_sub_officer()||is_admin()):?><a href="admin/users.php">👥 Users & Roles</a><a href="operational/list.php">📊 Review Reports</a><a href="institution/students.php">🎓 Student Presenty</a><a href="institution/wastigruh.php">🏠 Wastigruh Status</a><?php else:?><a href="work/list.php">✅ My Tasks</a><a href="records/list.php">📁 Records</a><a href="operational/create.php">📊 Daily Report</a><a href="files/list.php">📎 Documents</a><?php endif;?></div></div>
<div class="card"><h3>ITDP Monitoring</h3><p class="muted">Use daily entries for attendance and hostel facilities so officers can see shortages, issues and follow-up requirements in one place.</p><?php if(is_admin()||is_sub_officer()):?><a class="btn primary" href="admin/operations.php">Open Operations</a><?php else:?><a class="btn primary" href="notifications.php">View Alerts</a><?php endif;?></div></div><?php include 'includes/footer.php';?>
