<?php require_once '../includes/auth.php'; if(user()){redirect('../dashboard.php');}
$type=$_GET['type']??''; $allowed=['main_officer','sub_officer','clerk','ashram_shala','wastigruh']; if(!in_array($type,$allowed,true)){redirect('register.php');}
$err=$_GET['error']??'';
$meta=[
'main_officer'=>['Main Officer','🏛️','ITDP Main Officer / Administrator','District-level administration and overall platform control.'],
'sub_officer'=>['Sub Officer','👮','ITDP Sub Officer','Institution supervision, verification and monitoring.'],
'clerk'=>['Clerk / Data Entry','🧑‍💼','Clerk / Data Entry User','Enter daily records for an Ashram Shala or Wastigruh.'],
'ashram_shala'=>['Ashram Shala','🎓','Ashram Shala Superintendent','Student records, presenty and school reporting.'],
'wastigruh'=>['Wastigruh','🏠','Wastigruh Superintendent','Residents, meals, clothes, sports, inventory and facility monitoring.']][$type];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$meta[2]?> Registration</title><link rel="stylesheet" href="../assets/style.css"></head><body class="auth-bg"><div class="auth-shell"><div class="brand-panel"><div class="brand-mark">ITDP</div><div class="portal-icon"><?=$meta[1]?></div><h1><?=$meta[2]?></h1><p><?=$meta[3]?></p><div class="feature-list"><span>✓ Role-based dashboard</span><span>✓ Administrator approval</span><span>✓ Secure password authentication</span></div></div>
<div class="card auth-card"><a class="back-link" href="register.php">← Change registration type</a><h2><?=$meta[0]?> Registration</h2><p class="muted">New accounts require administrator approval.</p><?php if($err):?><div class="alert danger"><?=e($err)?></div><?php endif;?><form method="post" action="register_save.php"><?=csrf_field()?><input type="hidden" name="portal_type" value="<?=e($type)?>"><label>Full name</label><input name="name" required><label>Email</label><input name="email" type="email" autocomplete="email" required><label>Password</label><input name="password" type="password" minlength="8" autocomplete="new-password" required>
<?php if($type==='main_officer'): ?><label>Officer registration key</label><input name="registration_key" type="password" placeholder="Enter authorized setup key" required><p class="help">Use the secure key provided by the system administrator.</p>
<?php elseif($type==='sub_officer'): ?><label>Office / District Code</label><input name="office_code" placeholder="e.g. ITDP-YAVAT-01" required>
<?php else: ?><label>Institution</label><select name="institution_type" required><?php if($type==='ashram_shala'):?><option value="ashram_shala">Ashram Shala</option><?php elseif($type==='wastigruh'):?><option value="wastigruh">Wastigruh</option><?php else:?><option value="">Select institution</option><option value="ashram_shala">Ashram Shala</option><option value="wastigruh">Wastigruh</option><?php endif;?></select><label>Institution Code</label><input name="institution_code" placeholder="e.g. ASHRAM001 / WASTI001" required><?php endif; ?><button class="wide">Submit registration</button></form><p class="center">Already registered? <a href="login.php">Back to login</a></p></div></div></body></html>
