<?php include '../includes/header.php';$id=(int)($_GET['id']??0);$u=user();
if(is_admin()){$s=mysqli_prepare($conn,"SELECT t,u.name creator FROM work_tasks t JOIN users u ON u.id=t.created_by WHERE t.id=?");mysqli_stmt_bind_param($s,'i',$id);}
else{$s=mysqli_prepare($conn,"SELECT DISTINCT t,u.name creator FROM work_tasks t JOIN users u ON u.id=t.created_by LEFT JOIN task_assignees a ON a.task_id=t.id LEFT JOIN task_authorities ta ON ta.task_id=t.id WHERE t.id=? AND (a.user_id=? OR ta.user_id=?)");mysqli_stmt_bind_param($s,'iii',$id,$u['id'],$u['id']);}
mysqli_stmt_execute($s);$t=mysqli_fetch_assoc(mysqli_stmt_get_result($s));if(!$t)exit('Task not found or access denied.');
$re=mysqli_prepare($conn,"SELECT r.*,u.name FROM task_replies r JOIN users u ON u.id=r.user_id WHERE r.task_id=? ORDER BY r.id ASC");mysqli_stmt_bind_param($re,'i',$id);mysqli_stmt_execute($re);$rr=mysqli_stmt_get_result($re);?>
<div class="page-head"><div><p class="eyebrow">TASK #<?=$id?></p><h1><?=e($t['title'])?></h1><p class="muted">Created by <?=e($t['creator'])?> · Due <?=e($t['due_date']?:'—')?></p></div></div>
<div class="grid two"><div class="card"><h3>Task details</h3><p><?=nl2br(e($t['description']))?></p><p><span class="pill"><?=e($t['priority'])?></span> <span class="pill"><?=e($t['status'])?></span></p><?php if(!is_admin()):?><form method="post" action="reply.php"><?=csrf_field()?><input type="hidden" name="task_id" value="<?=$id?>"><label>Progress</label><input type="number" name="progress" min="0" max="100" value="<?=e($t['progress_percent'])?>"><label>Update / reply</label><textarea name="message" required placeholder="Describe work completed or request clarification"></textarea><button>Submit update</button></form><?php endif;?></div>
<div class="card"><h3>Updates</h3><?php while($x=mysqli_fetch_assoc($rr)):?><div class="reply"><b><?=e($x['name'])?></b><small><?=e($x['created_at'])?> · <?=e($x['progress_percent'])?>%</small><p><?=nl2br(e($x['message']))?></p></div><?php endwhile;?></div></div>
<?php include '../includes/footer.php';?>
